import Head from "next/head";
import styles from "@/styles/Home.module.scss";
import AddTodo from "@/components/addTodo";
import TodoCardList from "@/components/todoCardList";
import User from "@/components/user";

export default function Home() {
  return (
    <>
      <Head>
        <title>ToDo App @kirkgio92</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <User />
        <AddTodo />
        <TodoCardList />
      </main>
    </>
  );
}
