import Head from "next/head";
import styles from "@/styles/Home.module.scss";
import AddTodo from "@/components/addTodo";
import TodoCardList from "@/components/todoCardList";
import User from "@/components/user";
import Calendar from "@/components/calendar";
import { useState } from "react";
import Details from "./Details";

export default function Home() {
  const [showDetails, setShowDetails] = useState(false);
  const [data, setData] = useState(null);

  const showDetailsHandle = (dayStr) => {
    setData(dayStr);
    setShowDetails(true);
  };

  return (
    <>
      <Head>
        <title>ToDo App @kirkgio92</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <User />
        <Calendar showDetailsHandle={showDetailsHandle} />
        <br />
        {showDetails && <Details data={data} />}
        <AddTodo />
        <TodoCardList data={data} />
      </main>
    </>
  );
}
